package fr.robotv2.common.data.impl;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import fr.robotv2.common.reset.ResetService;

import java.util.UUID;

@DatabaseTable(tableName = "rtq_activequests")
public class ActiveQuest {

    @DatabaseField(columnName = "id", unique = true, generatedId = true)
    private int id;

    @DatabaseField(columnName = "owner")
    private UUID owner;

    @DatabaseField(columnName = "quest_id")
    private String questId;

    @DatabaseField(columnName = "reset_id")
    private String resetId;

    @DatabaseField(columnName = "done")
    private boolean done;

    @DatabaseField(columnName = "progress")
    private int progress = 0;

    @DatabaseField(columnName = "next_reset")
    private long nextReset;

    private boolean dirty = false;

    public ActiveQuest() {
        // Empty constructor. Necessary for orm-lite to work.
    }

    public ActiveQuest(UUID owner, String questId, ResetService service) {
        this(owner, questId, service.getId(), service.getNextExecution(), false, 0);
        markDirty(true);
    }

    public ActiveQuest(UUID owner, String questId, String resetId, long nextReset, boolean done, int progress) {
        this.owner = owner;
        this.questId = questId;
        this.resetId = resetId;
        this.done = done;
        this.progress = progress;
        this.nextReset = nextReset;
    }

    public int getAutoGeneratedId() {
        return this.id;
    }

    public UUID getOwner() {
        return owner;
    }

    public String getQuestId() {
        return questId;
    }

    public String getResetId() {
        return resetId;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean value) {
        this.done = value;
        markDirty(true);
    }

    public boolean hasEnded() {
        return System.currentTimeMillis() >= this.nextReset;
    }

    public int getProgress() {
        return progress;
    }

    public void incrementProgress() {
        incrementProgress(1);
    }

    public void incrementProgress(int value) {
        progress += value;
        markDirty(true);
    }

    public boolean isDirty() {
        return this.dirty;
    }

    public void markDirty(boolean value) {
        this.dirty = value;
    }
}
