# support is available on the discord server: https://discord.gg/nafAPKfC5M

options:
  debug: false
  player_move_event_threshold: 5
  anti-dupe:
    #should entity from spawner be able to increment entity quest ? (KILL, TAME, etc...)
    disable_spawners_progression: true
    #should placed block by creative player be able to increment block quest ? (BREAK etc...)
    count_block_from_creative: false
    #should items dropping from a previously placed block should be able to increment item quest (PICKUP etc...)
    count_items_from_placed_block: true
    # This option only work with PLACE type quest.
    # With this option to 'true', every broken block that match the specific PLACE quest AND that
    # have been previously placed by the player will DECREMENT the quest.
    count_breaking_placed_block: false
  bungeecord:
    enabled: false
    redis_address: 127.0.0.1
    redis_port: 6379

storage:
  # Default mode is "SQLITE".
  # Mode Available: SQLITE, MYSQL.
  mode: SQLITE
  mysql-credentials:
    # only use this if mode is "MYSQL"
    host: your-host
    port: your-port
    database: your-database
    username: your-username
    password: your-password
    useSSL: false

# paths to quest files
# File separator are supported.
quest-files:
  - "Qdaily.yml"
  - "Qweekly.yml"
  - "Qmonthly.yml"

# Represent the number of quest a player MUST have for each reset id.
# Players may need to reconnect to see their quest numbers changed.
# You may need to reset players while changing this to a lower number during game.
quest-assignment:
  DAILY: 1
  WEEKLY: 5
  MONTHLY: 3

# commands to be executed for a player when
# this one finish all quest in a reset service.
# get a list of reward here: https://robotv2.gitbook.io/wiki-rtq-robottimedquest/misc/reward-processor
quest-bulk-done:
  DAILY:
    - "[MESSAGE] Congratulations, you have done all the daily quest !"
    - "[COMMAND] give %player% gold_ingot 2"
    - "[EXP_LEVEL] 3"
  WEEKLY:
    - "[MESSAGE] Congratulations, you have done all the daily quest !"
    - "[COMMAND] give %player% gold_ingot 6"
    - "[EXP_LEVEL] 5"
  MONTHLY:
    - "[MESSAGE] Congratulations, you have done all the daily quest !"
    - "[COMMAND] give %player% gold_ingot 16"
    - "[EXP_LEVEL] 20"


cosmetics:
  # actionbar when the player increments a quest.
  actionbar:
    enabled: true
    progression_message: "%quest_display% &8| %quest_progressbar% &8| &7%quest_progression% &8/ &7%quest_required%"
  # title when the player finishes a quest.
  title:
    enabled: true
    fade-in: 10
    stay: 20
    fade-out: 10
    title: "&a&lCONGRATULATION %player%"
    subtitle: "&aYou have successfully done the quest: %quest_display%"
  bossbar:
    enabled: true
    progression_message: "%quest_display% &8| %quest_progressbar% &8| &7%quest_progression% &8/ &7%quest_required%"
    color: "WHITE"
    delay: 5