options:
  debug: false
  bungeecord: false
  anti-dupe:
    disable_spawners_progression: false
    disable_marking_creative_progression: false

storage:
  # Default mode is "SQLITE".
  # Mode Available: SQLITE, MYSQL.
  mode: SQLITE
  mysql-credentials:
    # only use this if mode is "MYSQL"
    host: your-host
    port: your-port
    database: your-database
    username: your-username
    password: your-password
    useSSL: false

quest-files:
  - "Qdaily.yml"
  - "Qweekly.yml"
  - "Qmonthly.yml"

quest-assignment:
  DAILY: 1
  WEEKLY: 5
  MONTHLY: 3

cosmetics:
  actionbar:
    enabled: true
    progression-message: "%quest_name% &8| %quest_progressbar% &8| &7%quest_progression% &8/ &7%quest_required%"
  title:
    enabled: true
    fade-in: 10
    stay: 20
    fade-out: 10
    title: "&a&lCONGRATULATION %player%"
    subtitle: "&aYou have successfully done the quest: %quest_name%"