options:
  bungeecord: false
  disable_spawners_progression: false

storage:
  # Default mode is "SQLITE".
  # Mode Available: SQLITE, MYSQL.
  mode: SQLITE
  mysql-credentials:
    # only use this if mode is "MYSQL"
    host: your-host
    port: your-port
    database: your-database
    username: your-username
    password: your-password
    useSSL: false

quest-files:
  - "Qdaily.yml"
  - "Qweekly.yml"
  - "Qmonthly.yml"

quest-assignment:
  DAILY: 1
  WEEKLY: 5
  MONTHLY: 3