name: RobotTimedQuest
version: '${project.version}'
main: fr.robotv2.bukkit.RTQBukkitPlugin
api-version: '1.13'
authors:
  - Robotv2
softdepend:
  - PlaceholderAPI
  - Vault
  - ItemAdder
  - Oraxen
  - MythicMob
  - EliteMobs
  - PyroFishingPro
